config/routes.rb
Rails.application.routes.draw do
  root "products#index"


  resources :products do
    resources :marks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mark.rb
class Mark < ActiveRecord::Base
  belongs_to :product
  validates_numericality_of :points, less_than: 101, greater_than_or_equal_to: 0

  def letter
    if points < 60
      return "F"
    end
    if points >= 60 && points < 75
      return "C"
    end
    if points >= 75 && points < 90
      return "B"
    end
    if points >= 90
      "A"
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :marks, dependent: :destroy
  validates :title, presence: true, length: {maximum: 250}
  validates :description, presence: true, length: {maximum: 500}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController

  def new
    @product = Product.find(params[:product_id])
    @mark = Mark.new
  end

  def create
    @products = Product.all
    @marks = Mark.all
    @product = Product.find(params[:product_id])
    @mark = @product.marks.create(params.require(:mark).permit(:points))
    if @mark.save
      render template: "products/index" , flash: {success: "Mark was added"}
    else
      render :new, flash: {alert: "Some bullshit has happened"}
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  #Read
  def index
    @products = Product.all
    @marks = Mark.all
  end

  #Create
  def new
    @product = Product.new
  end

  def create
    product = Product.new(params.require(:product).permit(:title, :description))
    if product.save
      redirect_to action: :index, flash: {success: "HEY! Product was added!!!"}
    else
      render :new, flash: {alert: "Some error occured"}
    end
  end

  #Destroy
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to action: :index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L6</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="style.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjs/6.6.4/math.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/marks/new.html.erb
<%= form_with model: [@product, @product.marks.build], local: true do |form| %>
  <div align="center" class="acrylic shadow">
    <div>
      <%= form.label :points %><br>
     <%= form.text_field :points %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/products/index.html.erb
<h1 align="center"> Submit your solution </h1>
<div id="place" class="acrylic shadow">
  <div class="func-buttons">
      <%= link_to "Add solution", new_product_path%>
  </div>
</div>
<div id="place" class="acrylic shadow">
  <% @products.each do |product| %>
    <% flag = false %>
    <% mark = Mark.new %>
    <% @marks.each do |m| %>
      <% if product.id == m.product_id %>
        <% mark = m %>
        <% flag = true %>
      <% end %>
    <% end %>
    <% if !flag %>
      <div class="shadow">
        <br>
        <b><%= product.title %> </b> <br>
        <%= product.description %> <br>
        <%= link_to "ADD Rating", new_product_mark_path(product) %>
        <%= link_to "Remove", product, method: :delete, data: {confirm: "U Sure?"} %> <br>
        <br>
      </div>
    <% else %>
      <div class="shadow">
        <br>
        <b><%= product.title %> </b> <br>
        <%= product.description %> <br>
        Rating <%= mark.letter %> [<%= mark.points %>]
        <%= link_to "Remove", product, method: :delete, data: {confirm: "U Sure?"} %> <br>
        <br>
      </div>
    <% end %>
  <% end %>
</div>

app/views/products/new.html.erb
<%= form_with model: @product, local: true do |form| %>
<div align="center" class="acrylic shadow">
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
</div>
<% end %>